module.exports = {
    darkMode: 'class',
    content: [
        './App.{js,jsx,ts,tsx}',
        './src/**/*.{js,jsx,ts,tsx}',
        './src/**/**/*.{js,jsx,ts,tsx}',
        './app/**/*.{js,jsx,ts,tsx}',
    ],
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors: {
                // primary: {
                //     0: 'var(--color-primary-0)',
                //     50: 'var(--color-primary-50)',
                //     100: 'var(--color-primary-100)',
                //     200: 'var(--color-primary-200)',
                //     300: 'var(--color-primary-300)',
                //     400: 'var(--color-primary-400)',
                //     500: 'var(--color-primary-500)',
                //     600: 'var(--color-primary-600)',
                //     700: 'var(--color-primary-700)',
                //     800: 'var(--color-primary-800)',
                //     900: 'var(--color-primary-900)',
                //     950: 'var(--color-primary-950)',
                // },
                primary: {
                    0: '#000',
                    10: '#001F2A',
                    20: '#003547',
                    30: '#004D65',
                    40: '#004D65',
                    50: '#0081A7',
                    60: '#039CCA',
                    70: '#3FB7E6',
                    80: '#6BD2FF',
                    90: '#BFE9FF',
                    95: '#E1F4FF',
                    99: '#EDF4FA',
                    100: '#FFF',
                },
                alert: {
                    success: '#44E187',
                    link: '#3EAEFF',
                    info: '#3EAEFF',
                    warning: '#FF9700',
                    error: '#FE5050',
                },
                neutral: {
                    0: '#000',
                    10: '#222',
                    20: '#383838',
                    30: '#4E4E4E',
                    40: '#666',
                    50: '#7F7F7F',
                    60: '#999',
                    70: '#B4B4B4',
                    80: '#CFCFCF',
                    90: '#E6E6E6',
                    95: '#F2F2F2',
                    99: '#FAFAFA',
                    100: '#FFF',
                },
                secondary: {
                    0: 'var(--color-secondary-0)',
                    50: 'var(--color-secondary-50)',
                    100: 'var(--color-secondary-100)',
                    200: 'var(--color-secondary-200)',
                    300: 'var(--color-secondary-300)',
                    400: 'var(--color-secondary-400)',
                    500: 'var(--color-secondary-500)',
                    600: 'var(--color-secondary-600)',
                    700: 'var(--color-secondary-700)',
                    800: 'var(--color-secondary-800)',
                    900: 'var(--color-secondary-900)',
                    950: 'var(--color-secondary-950)',
                },
                tertiary: {
                    50: 'var(--color-tertiary-50)',
                    100: 'var(--color-tertiary-100)',
                    200: 'var(--color-tertiary-200)',
                    300: 'var(--color-tertiary-300)',
                    400: 'var(--color-tertiary-400)',
                    500: 'var(--color-tertiary-500)',
                    600: 'var(--color-tertiary-600)',
                    700: 'var(--color-tertiary-700)',
                    800: 'var(--color-tertiary-800)',
                    900: 'var(--color-tertiary-900)',
                    950: 'var(--color-tertiary-950)',
                },
                error: {
                    0: 'var(--color-error-0)',
                    50: 'var(--color-error-50)',
                    100: 'var(--color-error-100)',
                    200: 'var(--color-error-200)',
                    300: 'var(--color-error-300)',
                    400: 'var(--color-error-400)',
                    500: 'var(--color-error-500)',
                    600: 'var(--color-error-600)',
                    700: 'var(--color-error-700)',
                    800: 'var(--color-error-800)',
                    900: 'var(--color-error-900)',
                    950: 'var(--color-error-950)',
                },
                success: {
                    0: 'var(--color-success-0)',
                    50: 'var(--color-success-50)',
                    100: 'var(--color-success-100)',
                    200: 'var(--color-success-200)',
                    300: 'var(--color-success-300)',
                    400: 'var(--color-success-400)',
                    500: 'var(--color-success-500)',
                    600: 'var(--color-success-600)',
                    700: 'var(--color-success-700)',
                    800: 'var(--color-success-800)',
                    900: 'var(--color-success-900)',
                    950: 'var(--color-success-950)',
                },
                warning: {
                    0: 'var(--color-warning-0)',
                    50: 'var(--color-warning-50)',
                    100: 'var(--color-warning-100)',
                    200: 'var(--color-warning-200)',
                    300: 'var(--color-warning-300)',
                    400: 'var(--color-warning-400)',
                    500: 'var(--color-warning-500)',
                    600: 'var(--color-warning-600)',
                    700: 'var(--color-warning-700)',
                    800: 'var(--color-warning-800)',
                    900: 'var(--color-warning-900)',
                    950: 'var(--color-warning-950)',
                },
                info: {
                    0: 'var(--color-info-0)',
                    50: 'var(--color-info-50)',
                    100: 'var(--color-info-100)',
                    200: 'var(--color-info-200)',
                    300: 'var(--color-info-300)',
                    400: 'var(--color-info-400)',
                    500: 'var(--color-info-500)',
                    600: 'var(--color-info-600)',
                    700: 'var(--color-info-700)',
                    800: 'var(--color-info-800)',
                    900: 'var(--color-info-900)',
                    950: 'var(--color-info-950)',
                },
                typography: {
                    0: 'var(--color-typography-0)',
                    50: 'var(--color-typography-50)',
                    100: 'var(--color-typography-100)',
                    200: 'var(--color-typography-200)',
                    300: 'var(--color-typography-300)',
                    400: 'var(--color-typography-400)',
                    500: 'var(--color-typography-500)',
                    600: 'var(--color-typography-600)',
                    700: 'var(--color-typography-700)',
                    800: 'var(--color-typography-800)',
                    900: 'var(--color-typography-900)',
                    950: 'var(--color-typography-950)',
                    white: '#FFFFFF',
                    gray: '#D4D4D4',
                    black: '#181718',
                },
                outline: {
                    0: 'var(--color-outline-0)',
                    50: 'var(--color-outline-50)',
                    100: 'var(--color-outline-100)',
                    200: 'var(--color-outline-200)',
                    300: 'var(--color-outline-300)',
                    400: 'var(--color-outline-400)',
                    500: 'var(--color-outline-500)',
                    600: 'var(--color-outline-600)',
                    700: 'var(--color-outline-700)',
                    800: 'var(--color-outline-800)',
                    900: 'var(--color-outline-900)',
                    950: 'var(--color-outline-950)',
                },
                background: {
                    0: 'var(--color-background-0)',
                    50: 'var(--color-background-50)',
                    100: 'var(--color-background-100)',
                    200: 'var(--color-background-200)',
                    300: 'var(--color-background-300)',
                    400: 'var(--color-background-400)',
                    500: 'var(--color-background-500)',
                    600: 'var(--color-background-600)',
                    700: 'var(--color-background-700)',
                    800: 'var(--color-background-800)',
                    900: 'var(--color-background-900)',
                    950: 'var(--color-background-950)',
                    error: 'var(--color-background-error)',
                    warning: 'var(--color-background-warning)',
                    muted: 'var(--color-background-muted)',
                    success: 'var(--color-background-success)',
                    light: '#FBFBFB',
                    dark: '#181719',
                },
            },
            fontFamily: {
                heading: undefined,
                body: undefined,
                mono: undefined,
            },
            fontWeight: {
                hairline: '100',
                extraBlack: '950',
            },
            fontSize: {
                '2xs': '10px',
            },
        },
        plugins: [],
    },
};
