service: uitbuoy

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  region: ap-southeast-1
  role: arn:aws:iam::519048229161:role/uitbuoy_admin
  runtime: nodejs20.x

functions:
  uitbuoy:
    handler: dist/main.handler
    events:
      - http:
          cors: true
          method: ANY
          path: /
      - http:
          cors: true
          method: ANY
          path: "{proxy+}"
