service: uitbuoy-api

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs20.x

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          cors: true
          method: ANY
          path: /
      - http:
          cors: true
          method: ANY
          path: "{proxy+}"
