name: Deploy api to AWS Lambda (Official)
on:
    push:
        branches:
            - UITBOUY-32-deploy-api
        tags:
            - release/api/official/**

jobs:
    deploy:
        environment: production
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install --filter=api --no-frozen-lockfile
            - name: Build code
              run: pnpm run --filter=api build-webpack
            - name: Zip code
              uses: montudor/action-zip@v1
              with:
                  args: zip -qq -r ./bundle.zip ./apps/api/dist
            - name: Upload to lambda
              uses: appleboy/lambda-action@v0.1.9
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_region: ${{ secrets.AWS_REGION }}
                  zip_file: bundle.zip
                  function_name: uitbuoy
                  handler: apps/api/dist/serverless.handler
                  role: arn:aws:iam::519048229161:role/uitbuoy_admin
                  runtime: nodejs20.x
                  environment: ENVIRONMENT=${{ secrets.ENVIRONMENT }}, APP_PORT=${{ secrets.APP_PORT }}, MAIN_DB_HOST=${{ secrets.MAIN_DB_HOST }}, MAIN_DB_PORT=${{ secrets.MAIN_DB_PORT }}, MAIN_DB_USERNAME=${{ secrets.MAIN_DB_USERNAME }}, MAIN_DB_PASSWORD=${{ secrets.MAIN_DB_PASSWORD }}, MAIN_DB_NAME=${{ secrets.MAIN_DB_NAME }}, LOGGER_DB_CONNECTION_URI=${{ secrets.LOGGER_DB_CONNECTION_URI }},
