name: Build server from source
on:
  push:
    branches:
      - UITBOUY-32-deploy-api
      - release/**
  pull_request:
    branches:
      - UITBOUY-32-deploy-api
      - release/**

jobs:
  deploy_source:
    needs: [build]
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: gorush
          source: example/index.js
